feat:update job

diff --git a/.github/workflows/github-actions-adb-sync.yml b/.github/workflows/github-actions-adb-sync.yml
--- a/.github/workflows/github-actions-adb-sync.yml
+++ b/.github/workflows/github-actions-adb-sync.yml
@@ -40,17 +40,22 @@ jobs:
     - run: git config --global user.email "automation@101digital.io"
     - run: git config --global user.name "Github Actions"
     - shell: bash
-      run: >
-        git config --global init.defaultBranch develop &&
-        git remote add external https://${{ secrets.EXTERNAL_GIT_TOKEN }}@${{ inputs.externalGitDomains }}/${{inputs.repo}}.git &&
-        git fetch external ${{ inputs.externalBranch }} &&
-        git remote add internal git@github.com:${{ inputs.internalOwner }}/${{ inputs.repo}}.git &&
-        git fetch internal ${{ inputs.internalBranch }} &&
+      run: |
+        git config --global init.defaultBranch develop
+        git remote add external https://${{ secrets.EXTERNAL_GIT_TOKEN }}@${{ inputs.externalGitDomains }}/${{inputs.repo}}.git
+        git fetch external ${{ inputs.externalBranch }}
+        git remote add internal git@github.com:${{ inputs.internalOwner }}/${{ inputs.repo}}.git
+        git fetch internal ${{ inputs.internalBranch }}
         git checkout -b working-branch internal/${{ inputs.internalBranch }}
-    - run: echo 'result=$(git merge external/${{ inputs.externalBranch }} --allow-unrelated-histories --no-edit | head -n 1)'  >> $GITHUB_OUTPUT
+    - run: |
+        echo "result<<EOF" >> $GITHUB_OUTPUT
+        git merge external/${{ inputs.externalBranch }} --allow-unrelated-histories --no-edit >> $GITHUB_OUTPUT
+        echo 'EOF' >> $GITHUB_OUTPUT
       id: merge
     - name: check merge status
-      run: echo "::error::Code is not in sync ${{ inputs.repo}}" && exit 1
+      run: |
+        echo ${{ steps.merge.outputs.result }}
+        echo "::error::Code is not in sync ${{ inputs.repo}}" && exit 1
       if: steps.merge.outputs.result != 'Already up to date.'
 
 
